---
env:
  contexts:
  - name: "Firing Range"
    urls:
    - "https://public-firing-range.appspot.com/reverseclickjacking/"
    includePaths: []
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- name: "add-script"
  type: script
  parameters:
    action: add
    type: standalone
    file: /zap/wrk/firing-range-score.js
- parameters: {}
  name: "spider"
  type: "spider"
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- name: "run-script"
  type: script
  parameters:
    action: run
    type: standalone
    name: firing-range-score.js
